### ISSUE TITLE
Compilation broken with Coq 8.14

### ISSUE THREAD

**Issue by Zimmi48** [coq-community/goedel#11]
FWIW, the compilation of Goedel fails with Coq 8.14 with the following error:

```
 File "./theories/chRem.v", line 257, characters 0-6:
Error: The reference double was not found in the current environment.
```

**Comment by Zimmi48** [comment]
Oh, I think the problem was that I was testing 8.12.0, whereas 8.13.0 is compatible with 8.14.

**Comment by Casteran** [comment]
OK, I can add the command `Set Apply With Renaming` and try to push.
