### ISSUE TITLE
installing coq-goedel makes Coq downgrade to 8.10.2 (on opam)

### ISSUE THREAD

**Issue by Casteran** [coq-community/goedel#2]
@palmskog 

I tried to install coq-goedel as indicated on the README, but it seems to be compatible only with CoqV8.10

**Comment by Casteran** [comment]
The message from opam (2.0.0) :

opam install coq-goedel
The following actions will be performed:
  ∗ install   conf-perl-string-shellquote 1
          [required by camlp5]
  ↘ downgrade coq                         8.12.2 to 8.10.2
          [required by coq-goedel]
   ...

The same issue occurs also in coq-pocklington

**Comment by palmskog** [comment]
@Casteran there are currently only "old" releases (compatible with <= 8.10) of goedel in the opam archive. If you want, I can make a release of the current versions of goedel and pocklington (compatible with 8.12 and seemingly 8.13) and put them on the archive.

**Comment by Casteran** [comment]
It would be nice.  I plan to use some of goedel stuff in hydra-battles (which has a few 8.12 specific commands).
Thank you for your help!

**Comment by palmskog** [comment]
@Casteran the pocklington and goedel releases compatible with 8.12 (and 8.13+beta1) are now out on opam, so you should be able to do `opam update` and then install them without issues. I'm closing this issue, but please reopen if something goes awry.
