### ISSUE TITLE
modificactions to goedel

### ISSUE THREAD

**Issue by Casteran** [coq-community/goedel#4]
@palmskog @Zimmi48 

goedel is a great contribution, and is worth maintaining !

Nevertheless, if we want to use it also as a library of primitive recursive functions (for instance in coq-hydra-battles), there is a lot of work to be done.

  - add documentation (files of examples, coqdoc comments, text), especially for functions defined by interactive proofs.
  - add tactics 
  - use "modern" coq style (bullets, implicit arguments, type classes, ...)
  
I created a branch new-stuff for these improvements (which may take a long time)

**Comment by palmskog** [comment]
@Casteran maybe it is worthwhile to organize and package the primitive recursive function theory separately? This would be some kind of inverse of how two separate developments were brought together in hydra-battles. We just got some experience of setting up boilerplate and continuous integration for a monorepo with dependencies (https://github.com/coq-community/topology).

**Comment by Casteran** [comment]
@palmskog 
Ok, it's also a suggestion from @Zimmi48 . 
There are 8/46 modules  which depend on pocklington:
PRreprsentable, chRem, codSysPrf, fixpoint,  goedel1, goedel2,, rosser, and rosserPA.
So, the 38 remaining modules may be in a big theory on PR functions and basis of PA.
The rest would be specific to Gödel's theorem.

**Comment by palmskog** [comment]
@Casteran this kind of split sounds quite straightforward to do, but it takes some fiddling to get the boilerplate files right. What should the namespace and package be called? PrimitiveRecursion and coq-primitive-recursion? Let me know what you think and if we should try it in the `new-stuff` branch.

**Comment by Casteran** [comment]
@palmskog 

Yes, PrimitiveRecursion and coq-primitive-recursion are OK. I like  alst the shorter names Ackermann and coq-ackermann.
What do you think of them?
 In new-stuff, the file primRec.v is bulletized and indented, and there is  a small new file : PrimRecExamples.v (under development, but OK).

**Comment by palmskog** [comment]
I think Ackermann is a good name, and it fits well together with "Goedel". So, unless there are objections, I will split up `new-stuff` later tonight.

**Comment by palmskog** [comment]
There are now Git-based opam packages `coq-goedel` and `coq-ackermann` in the `extra-dev` opam repo that can be depended on in hydra-battles, for example.

While we could do an actual release/tag of the split `goedel` repo, I'm hesitant to do this right now since we only build the packages with Dune, which is not yet long-term-supported for Coq use. 

@Zimmi48 do you have any opinion how this should be handled? We could add boilerplate to make the packages build separately with `coq_makefile`, but this would mean introducing quite a lot of duplication, just to be Dune-free in the `released` opam repo. Other projects using Dune will have similar dilemmas.

**Comment by Zimmi48** [comment]
I wouldn't worry about this and publish into `released` with a dependency on Dune. If early versions of the Coq language happened to be dropped in future Dune versions, we would just need to add an upper bound to the Dune version constraint (but we don't even need to do that yet).

Another suggestion I made is that the content of the goedel repository could be moved to the hydra-battles repository if it allows working on both at once more easily.

**Comment by Casteran** [comment]
@palmskog  @Zimmi48 
To be more precise, It would be OK to move just Ackermann into hydra-battles, letting the other files as Karl did.
For instance, if I want to prove formally that the Ackermann function is not PR (an "exercise" in Ackerman), I could use an already existing  library hydra-battles/ordinals/Prelude/Iterates.v  (containing monotony properties on iteration).

If you agree, I can experiment on a new branch of hydra-battles, and we see if its OK to change.

**Comment by Casteran** [comment]
@palmskog @Zimmi48 
I created a branch with-ackermann: seems to work nicely (I modified _CoqProject, but not the dune stuff)

**Comment by palmskog** [comment]
All the big reshuffling of content appears to be done now. I trust @Casteran will let us know how things go after this point, and if more meta-project discussion is needed.
