### ISSUE TITLE
Release for 8.13

### ISSUE THREAD

**Issue by palmskog** [coq-community/goedel#8]
Given that there are changes planned upstream to the Ackermann library in hydra-battles (https://github.com/coq-community/hydra-battles/issues/31), this could be a good time to make a timestamp/release of goedel that works with hydra-battles 0.4 and Coq 8.13 (and 8.12). After the release, we can restrict this project to 8.13+ like hydra-battles.

@Casteran what do you think? I can do the release if you think it's a good idea.

**Comment by Casteran** [comment]
Looks to be a good idea, thanks !
When I have completed a first pass of the adaptation of the doc to Alectryon, I’ll come back to the issue #31.

**Comment by palmskog** [comment]
This is done now, so closing. I think it should be fine to refactor stuff here now since we have a checkpoint that works for 8.13 (and very likely 8.14 as well).
